version: "2"
run:
  issues-exit-code: 1
  tests: true
linters:
  enable:
    - bodyclose
    - nakedret
    - revive
    - unconvert
    - unparam
  disable:
    - depguard
    - dupl
    - gochecknoglobals
    - gochecknoinits
    - goconst
    - gocritic
    - gocyclo
    - gosec
    - lll
    - misspell
    - prealloc
  settings:
    dupl:
      threshold: 100
    errcheck:
      check-type-assertions: true
      check-blank: true
    goconst:
      min-len: 3
      min-occurrences: 3
    gocritic:
      disabled-checks:
        - wrapperFunc
      enabled-tags:
        - performance
        - style
        - experimental
    gocyclo:
      min-complexity: 10
    govet:
      enable:
        - shadow
      settings:
        printf:
          funcs:
            - (github.com/golangci/golangci-lint/pkg/logutils.Log).Infof
            - (github.com/golangci/golangci-lint/pkg/logutils.Log).Warnf
            - (github.com/golangci/golangci-lint/pkg/logutils.Log).Errorf
            - (github.com/golangci/golangci-lint/pkg/logutils.Log).Fatalf
    lll:
      line-length: 140
    misspell:
      locale: US
    nakedret:
      max-func-lines: 30
    prealloc:
      simple: true
      range-loops: true
      for-loops: false
    revive:
      rules:
        - name: var-naming
          arguments:
            - []
            - - SDN
    unparam:
      check-exported: false
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - internal/pkg/dsrpc/media_server.autogen.go
      - internal/pkg/dsrpc/schedule_client.autogen.go
      - internal/pkg/dsrpc/media_client.autogen.go
      - internal/pkg/dsrpc/schedule_server.autogen.go
      - api/kitex_gen/
      - api/proto_gen/
      - api/hertz_gen/
      - test/mocks/
      - third_party$
      - builtin$
      - examples$
issues:
  max-issues-per-linter: 0
  max-same-issues: 0
  new: false
formatters:
  enable:
    - gofmt
    - goimports
  settings:
    gofmt:
      simplify: true
    goimports:
      local-prefixes:
        - code.byted.org/bytertc/schedule
  exclusions:
    generated: lax
    paths:
      - internal/pkg/dsrpc/media_server.autogen.go
      - internal/pkg/dsrpc/schedule_client.autogen.go
      - internal/pkg/dsrpc/media_client.autogen.go
      - internal/pkg/dsrpc/schedule_server.autogen.go
      - api/kitex_gen/
      - api/proto_gen/
      - api/hertz_gen/
      - test/mocks/
      - third_party$
      - builtin$
      - examples$
